### PR TITLE
Music and Genre class initialization

### LINKED ISSUE #31: [1.0pt] Setting up MusicAlbum properties
All MusicAlbum class properties visible in the diagram should be defined and set up in the constructor method.

### LINKED ISSUE #32: [1.0pt] Setting up Genres properties #11
All Genre class properties visible in the diagram should be defined and set up in the constructor method.

### LINKED ISSUE #33: [2.0pt] Implement methods:
*  add_item method in the Genre class
- should take an instance of the Item class as an input
- should add the input item to the collection of items
- should add self as a property of the item object (by using the correct setter from the item object)
* can_be_archived?() in the MusicAlbum class
- should override the method from the parent class
- should return true if parent's method returns true AND if on_spotify equals true
- otherwise, it should return false

### LINKED ISSUE #38: [0.5pt]Create MusicAlbum class in a separate .rb file.
Initializing MusicAlbum class and setting parameters

### PR DESCRIPTION
**Pull request by usorfaitheloho**
## Implement methods:
- add_item method in the Genre class
 should take an instance of the Item class as an input
should add the input item to the collection of items
should add self as a property of the item object (by using the correct setter from the item object)
can_be_archived?() in the MusicAlbum class
should override the method from the parent class
should return true if parent's method returns true AND if on_spotify equals true
otherwise, it should return false

### CODE REVIEW

**Review by bushmusi — CHANGES_REQUESTED** [review]
Hi @usorfaitheloho 

### Required changes ♻️ 
You have done a great job so far.  Please try to fix **linter error**

**Comment by usorfaitheloho** [comment]
Thanks @bushmusi  😄 
I have fixed them

**Comment by bushmusi** [comment]
> Thanks @bushmusi 😄 I have fixed them

They were indentation error 👍

**Review by bushmusi — APPROVED** [review]
Hi @usorfaitheloho 

## Status Approved 🎓

There is nothing but it is time to merge it

**Comment by usorfaitheloho** [comment]
Thanks @bushmusi for the review

**Pull request merged**
